# Generated by Django 3.0.2 on 2020-01-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_id', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('speciality', models.CharField(max_length=100)),
                ('resonforconsulation', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
