# Generated by Django 3.0.2 on 2020-01-13 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('doctordemo', '0002_pharmacy_pharmacy_details'),
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_name', to='doctordemo.Doctor_profiles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='patients_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients_name', to='patients.Patients'),
            preserve_default=False,
        ),
    ]
