# Generated by Django 3.0.2 on 2020-01-11 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('family_member', models.IntegerField()),
                ('action', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('patients', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(null=True, upload_to='Report_file')),
                ('file_size', models.IntegerField()),
                ('date_uploaded', models.DateField()),
                ('action', models.CharField(max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='patients.Patients')),
            ],
        ),
        migrations.CreateModel(
            name='Family_Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relations_to_patients', models.CharField(max_length=100)),
                ('profiles', models.ImageField(null=True, upload_to='Images')),
                ('familtpatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patients.Patients')),
            ],
        ),
    ]
