# Generated by Django 3.0.2 on 2020-01-11 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('doctordemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveConsulting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('call_type', models.CharField(choices=[('audio call', 'audio call'), ('video call', 'video call')], max_length=15)),
                ('status', models.CharField(max_length=100)),
                ('charge', models.FloatField()),
                ('doctors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorliveconsulting', to='doctordemo.Doctor_profiles')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientsliveconsulting', to='patients.Patients')),
                ('reports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportliveconsulting', to='patients.Report')),
            ],
        ),
    ]
