# Generated by Django 3.0.2 on 2020-01-11 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experince', models.CharField(blank=True, max_length=256, null=True)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('blood_Group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('action', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('charge', models.IntegerField()),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_degree', models.CharField(max_length=100)),
                ('university_college', models.CharField(max_length=255)),
                ('passing_year', models.CharField(max_length=4)),
                ('doctor_profiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='doctordemo.Doctor_profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.FileField(null=True, upload_to='FIlres')),
                ('date_uploaded', models.DateField()),
                ('file_size', models.IntegerField()),
                ('action', models.CharField(max_length=50)),
                ('doctor_documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_documents', to='doctordemo.Doctor_profiles')),
            ],
        ),
    ]
