# Generated by Django 3.0.2 on 2020-01-13 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursereportdata',
            name='nursedata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursedata', to='doctorhome.NurseData'),
        ),
    ]
