# Generated by Django 3.0.2 on 2020-01-11 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctordemo', '__first__'),
        ('patients', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('charge', models.FloatField()),
                ('mobile_no', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtest', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('charge', models.IntegerField()),
                ('file_name', models.CharField(max_length=100)),
                ('files', models.FileField(null=True, upload_to='diagnosticfiles')),
                ('diagnostics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic', to='diagnostic.Diagnostic')),
                ('doctordiagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctordiagnostic', to='doctordemo.Doctor_profiles')),
                ('patientpatients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientsdiagnostic', to='patients.Patients')),
            ],
        ),
    ]
